name: Build and Deploy Worker

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          npx wrangler deploy --dry-run --outdir=dist
          # npx javascript-obfuscator dist/index.js --output _index.js

      - name: Commit and push built worker
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/index.js -f
          git commit -m "Automated build: update dist/index.js"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}